/**
 * @file scpi_commands.cpp
 * 
 * Autogenerated SCPI commands trie and handler pointers.
 * Generated from App definition.
 * 
 */

#include <t76/scpi_command.hpp>
#include <t76/scpi_trie.hpp>
#include <t76/scpi_interpreter.hpp>

namespace T76 {
    class App {
    public:
        void _queryIDN(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::App> &);
    };
}

namespace T76::SCPI {

/*
 * Memory Usage Estimate for RP2040:
 * 
 * Trie Structure:
 *   - Total nodes: 6
 *   - Children arrays: 5
 *   - Node size: 8 bytes each
 *   - Trie memory: 48 bytes
 * 
 * Command System:
 *   - Commands: 1 (12 bytes)
 *   - Parameter descriptors: 0 bytes
 *   - String literals: 0 bytes
 * 
 * Total Memory Usage:
 *   - Code/Data (Flash): 60 bytes (0.00% of 2MB)
 *   - Runtime (SRAM): 64 bytes (0.02% of 264KB)
 * 
 * Performance Characteristics:
 *   - Average lookup depth: ~5.0 character comparisons
 *   - Memory access pattern: Sequential (cache-friendly)
 *   - Space complexity: O(total_command_chars)
 */    // Parameter descriptors for each command
    // Trie structure
    const TrieNode _node__starIDN_children[] = {
        { '?', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 0 } // Terminal: *IDN?
    };
    const TrieNode _node__starID_children[] = {
        { 'N', 0, 1, _node__starIDN_children, 0 }
    };
    const TrieNode _node__starI_children[] = {
        { 'D', 0, 1, _node__starID_children, 0 }
    };
    const TrieNode _node__star_children[] = {
        { 'I', 0, 1, _node__starI_children, 0 }
    };
    const TrieNode _root_children[] = {
        { '*', 0, 1, _node__star_children, 0 }
    };
    template<>
    const TrieNode T76::SCPI::Interpreter<T76::App>::_trie = { '\0', 0, 1, _root_children, 0 };

    // Command handlers and parameters
    template<>
    const Command<T76::App> T76::SCPI::Interpreter<T76::App>::_commands[] = {
        { &T76::App::_queryIDN, 0, nullptr }, // *IDN?
    };

    template<>
    const size_t T76::SCPI::Interpreter<T76::App>::_commandCount = 1;

    template<>
    const size_t T76::SCPI::Interpreter<T76::App>::_maxParameterCount = 0;

} // namespace
