/**
 * @file test_commands.cpp
 * 
 * Autogenerated SCPI commands trie and handler pointers.
 * Generated from ConcreteInterpreter definition.
 * 
 */

#include "command.hpp"
#include "trie.hpp"
#include "interpreter.hpp"

namespace T76::SCPI {
    class ConcreteInterpreter {
    public:
        void _testSimple(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _queryTestSimple(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testMixedCase(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testABDSimple(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testNumber(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testString(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testBoolean(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testEnum(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testMultiTwo(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testOptionalSingle(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testOptionalMultiple(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testInteger(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testFloat(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testRange(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testQuotedString(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testEnumMixed(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testEnumNumeric(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _queryTestParam(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _queryTestMulti(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testErrorSimulate(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _testErrorInvalid(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
        void _querySystemError(const std::vector<T76::SCPI::ParameterValue> &, T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter> &);
    };
}

namespace T76::SCPI {

/*
 * Memory Usage Estimate for RP2040:
 * 
 * Trie Structure:
 *   - Total nodes: 223
 *   - Children arrays: 201
 *   - Node size: 8 bytes each
 *   - Trie memory: 1784 bytes
 * 
 * Command System:
 *   - Commands: 22 (264 bytes)
 *   - Parameter descriptors: 368 bytes
 *   - String literals: 152 bytes
 * 
 * Total Memory Usage:
 *   - Code/Data (Flash): 2568 bytes (0.12% of 2MB)
 *   - Runtime (SRAM): 64 bytes (0.02% of 264KB)
 * 
 * Performance Characteristics:
 *   - Average lookup depth: ~17.3 character comparisons
 *   - Memory access pattern: Sequential (cache-friendly)
 *   - Space complexity: O(total_command_chars)
 */    // Parameter descriptors for each command
    const char* const command_7_param_0_choices[] = {
        "OPTION1",
        "OPTION2",
        "OPTION3",
        "DEFAULT",
    };

    const char* const command_10_param_2_choices[] = {
        "RED",
        "GREEN",
        "BLUE",
    };

    const char* const command_15_param_0_choices[] = {
        "CamelCase",
        "snake_case",
        "UPPERCASE",
        "lowercase",
    };

    const char* const command_16_param_0_choices[] = {
        "OPTION1",
        "OPTION2",
        "OPTION10",
        "OPTION100",
    };

    const char* const command_18_param_1_choices[] = {
        "VOLTAGE",
        "CURRENT",
        "POWER",
        "STATUS",
    };

    const ParameterDescriptor command_3_params[] = {
        {
            ParameterType::ArbitraryData,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_4_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_5_params[] = {
        {
            ParameterType::String,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_6_params[] = {
        {
            ParameterType::Boolean,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_7_params[] = {
        {
            ParameterType::Enum,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 4,
            .choices = command_7_param_0_choices
        },
    };

    const ParameterDescriptor command_8_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
        {
            ParameterType::String,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_9_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
        {
            ParameterType::String,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_10_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
        {
            ParameterType::String,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
        {
            ParameterType::Enum,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 3,
            .choices = command_10_param_2_choices
        },
    };

    const ParameterDescriptor command_11_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_12_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_13_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_14_params[] = {
        {
            ParameterType::String,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_15_params[] = {
        {
            ParameterType::Enum,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 4,
            .choices = command_15_param_0_choices
        },
    };

    const ParameterDescriptor command_16_params[] = {
        {
            ParameterType::Enum,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 4,
            .choices = command_16_param_0_choices
        },
    };

    const ParameterDescriptor command_17_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    const ParameterDescriptor command_18_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
        {
            ParameterType::Enum,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 4,
            .choices = command_18_param_1_choices
        },
    };

    const ParameterDescriptor command_19_params[] = {
        {
            ParameterType::Number,
            .defaultValue = {.numberValue = 0},
            .choiceCount = 0,
            .choices = nullptr
        },
    };

    // Trie structure
    const TrieNode _node_SYSTEM_colonERROR_children[] = {
        { '?', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 21 } // Terminal: SYSTEM:ERROR?
    };
    const TrieNode _node_SYSTEM_colonERRO_children[] = {
        { 'R', 0, 1, _node_SYSTEM_colonERROR_children, 0 }
    };
    const TrieNode _node_SYSTEM_colonERR_children[] = {
        { 'O', 0, 1, _node_SYSTEM_colonERRO_children, 0 }
    };
    const TrieNode _node_SYSTEM_colonER_children[] = {
        { 'R', 0, 1, _node_SYSTEM_colonERR_children, 0 }
    };
    const TrieNode _node_SYSTEM_colonE_children[] = {
        { 'R', 0, 1, _node_SYSTEM_colonER_children, 0 }
    };
    const TrieNode _node_SYSTEM_colon_children[] = {
        { 'E', 0, 1, _node_SYSTEM_colonE_children, 0 }
    };
    const TrieNode _node_SYSTEM_children[] = {
        { ':', 0, 1, _node_SYSTEM_colon_children, 0 }
    };
    const TrieNode _node_SYSTE_children[] = {
        { 'M', 0, 1, _node_SYSTEM_children, 0 }
    };
    const TrieNode _node_SYST_children[] = {
        { 'E', 0, 1, _node_SYSTE_children, 0 }
    };
    const TrieNode _node_SYS_children[] = {
        { 'T', 0, 1, _node_SYST_children, 0 }
    };
    const TrieNode _node_SY_children[] = {
        { 'S', 0, 1, _node_SYS_children, 0 }
    };
    const TrieNode _node_S_children[] = {
        { 'Y', 0, 1, _node_SY_children, 0 }
    };
    const TrieNode _node_TEST_colonABD_colonSIMPL_children[] = {
        { 'E', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 3 } // Terminal: TEST:ABD:SIMPLE
    };
    const TrieNode _node_TEST_colonABD_colonSIMP_children[] = {
        { 'L', 0, 1, _node_TEST_colonABD_colonSIMPL_children, 0 }
    };
    const TrieNode _node_TEST_colonABD_colonSIM_children[] = {
        { 'P', 0, 1, _node_TEST_colonABD_colonSIMP_children, 0 }
    };
    const TrieNode _node_TEST_colonABD_colonSI_children[] = {
        { 'M', 0, 1, _node_TEST_colonABD_colonSIM_children, 0 }
    };
    const TrieNode _node_TEST_colonABD_colonS_children[] = {
        { 'I', 0, 1, _node_TEST_colonABD_colonSI_children, 0 }
    };
    const TrieNode _node_TEST_colonABD_colon_children[] = {
        { 'S', 0, 1, _node_TEST_colonABD_colonS_children, 0 }
    };
    const TrieNode _node_TEST_colonABD_children[] = {
        { ':', 0, 1, _node_TEST_colonABD_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonAB_children[] = {
        { 'D', 0, 1, _node_TEST_colonABD_children, 0 }
    };
    const TrieNode _node_TEST_colonA_children[] = {
        { 'B', 0, 1, _node_TEST_colonAB_children, 0 }
    };
    const TrieNode _node_TEST_colonBOOLEA_children[] = {
        { 'N', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 6 } // Terminal: TEST:BOOLEAN
    };
    const TrieNode _node_TEST_colonBOOLE_children[] = {
        { 'A', 0, 1, _node_TEST_colonBOOLEA_children, 0 }
    };
    const TrieNode _node_TEST_colonBOOL_children[] = {
        { 'E', 0, 1, _node_TEST_colonBOOLE_children, 0 }
    };
    const TrieNode _node_TEST_colonBOO_children[] = {
        { 'L', 0, 1, _node_TEST_colonBOOL_children, 0 }
    };
    const TrieNode _node_TEST_colonBO_children[] = {
        { 'O', 0, 1, _node_TEST_colonBOO_children, 0 }
    };
    const TrieNode _node_TEST_colonB_children[] = {
        { 'O', 0, 1, _node_TEST_colonBO_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPT_colonSYNta_children[] = {
        { 'x', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOM_colonOPT_colonSYNt_children[] = {
        { 'a', 0, 1, _node_TEST_colonCOM_colonOPT_colonSYNta_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPT_colonSYN_children[] = {
        { 't', 0, 1, _node_TEST_colonCOM_colonOPT_colonSYNt_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPT_colonSY_children[] = {
        { 'N', uint8_t(TrieNodeFlags::Terminal), 1, _node_TEST_colonCOM_colonOPT_colonSYN_children, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOM_colonOPT_colonS_children[] = {
        { 'Y', 0, 1, _node_TEST_colonCOM_colonOPT_colonSY_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPT_colon_children[] = {
        { 'S', 0, 1, _node_TEST_colonCOM_colonOPT_colonS_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTional_colonSYNta_children[] = {
        { 'x', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOM_colonOPTional_colonSYNt_children[] = {
        { 'a', 0, 1, _node_TEST_colonCOM_colonOPTional_colonSYNta_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTional_colonSYN_children[] = {
        { 't', 0, 1, _node_TEST_colonCOM_colonOPTional_colonSYNt_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTional_colonSY_children[] = {
        { 'N', uint8_t(TrieNodeFlags::Terminal), 1, _node_TEST_colonCOM_colonOPTional_colonSYN_children, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOM_colonOPTional_colonS_children[] = {
        { 'Y', 0, 1, _node_TEST_colonCOM_colonOPTional_colonSY_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTional_colon_children[] = {
        { 'S', 0, 1, _node_TEST_colonCOM_colonOPTional_colonS_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTional_children[] = {
        { ':', 0, 1, _node_TEST_colonCOM_colonOPTional_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTiona_children[] = {
        { 'l', 0, 1, _node_TEST_colonCOM_colonOPTional_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTion_children[] = {
        { 'a', 0, 1, _node_TEST_colonCOM_colonOPTiona_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTio_children[] = {
        { 'n', 0, 1, _node_TEST_colonCOM_colonOPTion_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPTi_children[] = {
        { 'o', 0, 1, _node_TEST_colonCOM_colonOPTio_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOPT_children[] = {
        { ':', 0, 1, _node_TEST_colonCOM_colonOPT_colon_children, 0 },
        { 'i', 0, 1, _node_TEST_colonCOM_colonOPTi_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonOP_children[] = {
        { 'T', 0, 2, _node_TEST_colonCOM_colonOPT_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colonO_children[] = {
        { 'P', 0, 1, _node_TEST_colonCOM_colonOP_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_colon_children[] = {
        { 'O', 0, 1, _node_TEST_colonCOM_colonO_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPT_colonSYNta_children[] = {
        { 'x', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPT_colonSYNt_children[] = {
        { 'a', 0, 1, _node_TEST_colonCOMmand_colonOPT_colonSYNta_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPT_colonSYN_children[] = {
        { 't', 0, 1, _node_TEST_colonCOMmand_colonOPT_colonSYNt_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPT_colonSY_children[] = {
        { 'N', uint8_t(TrieNodeFlags::Terminal), 1, _node_TEST_colonCOMmand_colonOPT_colonSYN_children, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPT_colonS_children[] = {
        { 'Y', 0, 1, _node_TEST_colonCOMmand_colonOPT_colonSY_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPT_colon_children[] = {
        { 'S', 0, 1, _node_TEST_colonCOMmand_colonOPT_colonS_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTional_colonSYNta_children[] = {
        { 'x', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTional_colonSYNt_children[] = {
        { 'a', 0, 1, _node_TEST_colonCOMmand_colonOPTional_colonSYNta_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTional_colonSYN_children[] = {
        { 't', 0, 1, _node_TEST_colonCOMmand_colonOPTional_colonSYNt_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTional_colonSY_children[] = {
        { 'N', uint8_t(TrieNodeFlags::Terminal), 1, _node_TEST_colonCOMmand_colonOPTional_colonSYN_children, 2 } // Terminal: TEST:COMmand:OPTional:SYNtax
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTional_colonS_children[] = {
        { 'Y', 0, 1, _node_TEST_colonCOMmand_colonOPTional_colonSY_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTional_colon_children[] = {
        { 'S', 0, 1, _node_TEST_colonCOMmand_colonOPTional_colonS_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTional_children[] = {
        { ':', 0, 1, _node_TEST_colonCOMmand_colonOPTional_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTiona_children[] = {
        { 'l', 0, 1, _node_TEST_colonCOMmand_colonOPTional_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTion_children[] = {
        { 'a', 0, 1, _node_TEST_colonCOMmand_colonOPTiona_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTio_children[] = {
        { 'n', 0, 1, _node_TEST_colonCOMmand_colonOPTion_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPTi_children[] = {
        { 'o', 0, 1, _node_TEST_colonCOMmand_colonOPTio_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOPT_children[] = {
        { ':', 0, 1, _node_TEST_colonCOMmand_colonOPT_colon_children, 0 },
        { 'i', 0, 1, _node_TEST_colonCOMmand_colonOPTi_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonOP_children[] = {
        { 'T', 0, 2, _node_TEST_colonCOMmand_colonOPT_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colonO_children[] = {
        { 'P', 0, 1, _node_TEST_colonCOMmand_colonOP_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_colon_children[] = {
        { 'O', 0, 1, _node_TEST_colonCOMmand_colonO_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMmand_children[] = {
        { ':', 0, 1, _node_TEST_colonCOMmand_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMman_children[] = {
        { 'd', 0, 1, _node_TEST_colonCOMmand_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMma_children[] = {
        { 'n', 0, 1, _node_TEST_colonCOMman_children, 0 }
    };
    const TrieNode _node_TEST_colonCOMm_children[] = {
        { 'a', 0, 1, _node_TEST_colonCOMma_children, 0 }
    };
    const TrieNode _node_TEST_colonCOM_children[] = {
        { ':', 0, 1, _node_TEST_colonCOM_colon_children, 0 },
        { 'm', 0, 1, _node_TEST_colonCOMm_children, 0 }
    };
    const TrieNode _node_TEST_colonCO_children[] = {
        { 'M', 0, 2, _node_TEST_colonCOM_children, 0 }
    };
    const TrieNode _node_TEST_colonC_children[] = {
        { 'O', 0, 1, _node_TEST_colonCO_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonMIXE_children[] = {
        { 'D', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 15 } // Terminal: TEST:ENUM:MIXED
    };
    const TrieNode _node_TEST_colonENUM_colonMIX_children[] = {
        { 'E', 0, 1, _node_TEST_colonENUM_colonMIXE_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonMI_children[] = {
        { 'X', 0, 1, _node_TEST_colonENUM_colonMIX_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonM_children[] = {
        { 'I', 0, 1, _node_TEST_colonENUM_colonMI_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonNUMERI_children[] = {
        { 'C', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 16 } // Terminal: TEST:ENUM:NUMERIC
    };
    const TrieNode _node_TEST_colonENUM_colonNUMER_children[] = {
        { 'I', 0, 1, _node_TEST_colonENUM_colonNUMERI_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonNUME_children[] = {
        { 'R', 0, 1, _node_TEST_colonENUM_colonNUMER_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonNUM_children[] = {
        { 'E', 0, 1, _node_TEST_colonENUM_colonNUME_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonNU_children[] = {
        { 'M', 0, 1, _node_TEST_colonENUM_colonNUM_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colonN_children[] = {
        { 'U', 0, 1, _node_TEST_colonENUM_colonNU_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_colon_children[] = {
        { 'M', 0, 1, _node_TEST_colonENUM_colonM_children, 0 },
        { 'N', 0, 1, _node_TEST_colonENUM_colonN_children, 0 }
    };
    const TrieNode _node_TEST_colonENUM_children[] = {
        { ':', 0, 2, _node_TEST_colonENUM_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonENU_children[] = {
        { 'M', uint8_t(TrieNodeFlags::Terminal), 1, _node_TEST_colonENUM_children, 7 } // Terminal: TEST:ENUM
    };
    const TrieNode _node_TEST_colonEN_children[] = {
        { 'U', 0, 1, _node_TEST_colonENU_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonINVALI_children[] = {
        { 'D', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 20 } // Terminal: TEST:ERROR:INVALID
    };
    const TrieNode _node_TEST_colonERROR_colonINVAL_children[] = {
        { 'I', 0, 1, _node_TEST_colonERROR_colonINVALI_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonINVA_children[] = {
        { 'L', 0, 1, _node_TEST_colonERROR_colonINVAL_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonINV_children[] = {
        { 'A', 0, 1, _node_TEST_colonERROR_colonINVA_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonIN_children[] = {
        { 'V', 0, 1, _node_TEST_colonERROR_colonINV_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonI_children[] = {
        { 'N', 0, 1, _node_TEST_colonERROR_colonIN_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonSIMULAT_children[] = {
        { 'E', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 19 } // Terminal: TEST:ERROR:SIMULATE
    };
    const TrieNode _node_TEST_colonERROR_colonSIMULA_children[] = {
        { 'T', 0, 1, _node_TEST_colonERROR_colonSIMULAT_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonSIMUL_children[] = {
        { 'A', 0, 1, _node_TEST_colonERROR_colonSIMULA_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonSIMU_children[] = {
        { 'L', 0, 1, _node_TEST_colonERROR_colonSIMUL_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonSIM_children[] = {
        { 'U', 0, 1, _node_TEST_colonERROR_colonSIMU_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonSI_children[] = {
        { 'M', 0, 1, _node_TEST_colonERROR_colonSIM_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colonS_children[] = {
        { 'I', 0, 1, _node_TEST_colonERROR_colonSI_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_colon_children[] = {
        { 'I', 0, 1, _node_TEST_colonERROR_colonI_children, 0 },
        { 'S', 0, 1, _node_TEST_colonERROR_colonS_children, 0 }
    };
    const TrieNode _node_TEST_colonERROR_children[] = {
        { ':', 0, 2, _node_TEST_colonERROR_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonERRO_children[] = {
        { 'R', 0, 1, _node_TEST_colonERROR_children, 0 }
    };
    const TrieNode _node_TEST_colonERR_children[] = {
        { 'O', 0, 1, _node_TEST_colonERRO_children, 0 }
    };
    const TrieNode _node_TEST_colonER_children[] = {
        { 'R', 0, 1, _node_TEST_colonERR_children, 0 }
    };
    const TrieNode _node_TEST_colonE_children[] = {
        { 'N', 0, 1, _node_TEST_colonEN_children, 0 },
        { 'R', 0, 1, _node_TEST_colonER_children, 0 }
    };
    const TrieNode _node_TEST_colonMULTI_colonTW_children[] = {
        { 'O', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 8 } // Terminal: TEST:MULTI:TWO
    };
    const TrieNode _node_TEST_colonMULTI_colonT_children[] = {
        { 'W', 0, 1, _node_TEST_colonMULTI_colonTW_children, 0 }
    };
    const TrieNode _node_TEST_colonMULTI_colon_children[] = {
        { 'T', 0, 1, _node_TEST_colonMULTI_colonT_children, 0 }
    };
    const TrieNode _node_TEST_colonMULTI_children[] = {
        { ':', 0, 1, _node_TEST_colonMULTI_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonMULT_children[] = {
        { 'I', 0, 1, _node_TEST_colonMULTI_children, 0 }
    };
    const TrieNode _node_TEST_colonMUL_children[] = {
        { 'T', 0, 1, _node_TEST_colonMULT_children, 0 }
    };
    const TrieNode _node_TEST_colonMU_children[] = {
        { 'L', 0, 1, _node_TEST_colonMUL_children, 0 }
    };
    const TrieNode _node_TEST_colonM_children[] = {
        { 'U', 0, 1, _node_TEST_colonMU_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMBE_children[] = {
        { 'R', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 4 } // Terminal: TEST:NUMBER
    };
    const TrieNode _node_TEST_colonNUMB_children[] = {
        { 'E', 0, 1, _node_TEST_colonNUMBE_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonFLOA_children[] = {
        { 'T', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 12 } // Terminal: TEST:NUMERIC:FLOAT
    };
    const TrieNode _node_TEST_colonNUMERIC_colonFLO_children[] = {
        { 'A', 0, 1, _node_TEST_colonNUMERIC_colonFLOA_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonFL_children[] = {
        { 'O', 0, 1, _node_TEST_colonNUMERIC_colonFLO_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonF_children[] = {
        { 'L', 0, 1, _node_TEST_colonNUMERIC_colonFL_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonINTEGE_children[] = {
        { 'R', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 11 } // Terminal: TEST:NUMERIC:INTEGER
    };
    const TrieNode _node_TEST_colonNUMERIC_colonINTEG_children[] = {
        { 'E', 0, 1, _node_TEST_colonNUMERIC_colonINTEGE_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonINTE_children[] = {
        { 'G', 0, 1, _node_TEST_colonNUMERIC_colonINTEG_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonINT_children[] = {
        { 'E', 0, 1, _node_TEST_colonNUMERIC_colonINTE_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonIN_children[] = {
        { 'T', 0, 1, _node_TEST_colonNUMERIC_colonINT_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonI_children[] = {
        { 'N', 0, 1, _node_TEST_colonNUMERIC_colonIN_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonRANG_children[] = {
        { 'E', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 13 } // Terminal: TEST:NUMERIC:RANGE
    };
    const TrieNode _node_TEST_colonNUMERIC_colonRAN_children[] = {
        { 'G', 0, 1, _node_TEST_colonNUMERIC_colonRANG_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonRA_children[] = {
        { 'N', 0, 1, _node_TEST_colonNUMERIC_colonRAN_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colonR_children[] = {
        { 'A', 0, 1, _node_TEST_colonNUMERIC_colonRA_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_colon_children[] = {
        { 'F', 0, 1, _node_TEST_colonNUMERIC_colonF_children, 0 },
        { 'I', 0, 1, _node_TEST_colonNUMERIC_colonI_children, 0 },
        { 'R', 0, 1, _node_TEST_colonNUMERIC_colonR_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERIC_children[] = {
        { ':', 0, 3, _node_TEST_colonNUMERIC_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMERI_children[] = {
        { 'C', 0, 1, _node_TEST_colonNUMERIC_children, 0 }
    };
    const TrieNode _node_TEST_colonNUMER_children[] = {
        { 'I', 0, 1, _node_TEST_colonNUMERI_children, 0 }
    };
    const TrieNode _node_TEST_colonNUME_children[] = {
        { 'R', 0, 1, _node_TEST_colonNUMER_children, 0 }
    };
    const TrieNode _node_TEST_colonNUM_children[] = {
        { 'B', 0, 1, _node_TEST_colonNUMB_children, 0 },
        { 'E', 0, 1, _node_TEST_colonNUME_children, 0 }
    };
    const TrieNode _node_TEST_colonNU_children[] = {
        { 'M', 0, 2, _node_TEST_colonNUM_children, 0 }
    };
    const TrieNode _node_TEST_colonN_children[] = {
        { 'U', 0, 1, _node_TEST_colonNU_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonMULTIPL_children[] = {
        { 'E', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 10 } // Terminal: TEST:OPTIONAL:MULTIPLE
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonMULTIP_children[] = {
        { 'L', 0, 1, _node_TEST_colonOPTIONAL_colonMULTIPL_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonMULTI_children[] = {
        { 'P', 0, 1, _node_TEST_colonOPTIONAL_colonMULTIP_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonMULT_children[] = {
        { 'I', 0, 1, _node_TEST_colonOPTIONAL_colonMULTI_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonMUL_children[] = {
        { 'T', 0, 1, _node_TEST_colonOPTIONAL_colonMULT_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonMU_children[] = {
        { 'L', 0, 1, _node_TEST_colonOPTIONAL_colonMUL_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonM_children[] = {
        { 'U', 0, 1, _node_TEST_colonOPTIONAL_colonMU_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonSINGL_children[] = {
        { 'E', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 9 } // Terminal: TEST:OPTIONAL:SINGLE
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonSING_children[] = {
        { 'L', 0, 1, _node_TEST_colonOPTIONAL_colonSINGL_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonSIN_children[] = {
        { 'G', 0, 1, _node_TEST_colonOPTIONAL_colonSING_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonSI_children[] = {
        { 'N', 0, 1, _node_TEST_colonOPTIONAL_colonSIN_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colonS_children[] = {
        { 'I', 0, 1, _node_TEST_colonOPTIONAL_colonSI_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_colon_children[] = {
        { 'M', 0, 1, _node_TEST_colonOPTIONAL_colonM_children, 0 },
        { 'S', 0, 1, _node_TEST_colonOPTIONAL_colonS_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONAL_children[] = {
        { ':', 0, 2, _node_TEST_colonOPTIONAL_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIONA_children[] = {
        { 'L', 0, 1, _node_TEST_colonOPTIONAL_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTION_children[] = {
        { 'A', 0, 1, _node_TEST_colonOPTIONA_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTIO_children[] = {
        { 'N', 0, 1, _node_TEST_colonOPTION_children, 0 }
    };
    const TrieNode _node_TEST_colonOPTI_children[] = {
        { 'O', 0, 1, _node_TEST_colonOPTIO_children, 0 }
    };
    const TrieNode _node_TEST_colonOPT_children[] = {
        { 'I', 0, 1, _node_TEST_colonOPTI_children, 0 }
    };
    const TrieNode _node_TEST_colonOP_children[] = {
        { 'T', 0, 1, _node_TEST_colonOPT_children, 0 }
    };
    const TrieNode _node_TEST_colonO_children[] = {
        { 'P', 0, 1, _node_TEST_colonOP_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonMULTI_children[] = {
        { '?', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 18 } // Terminal: TEST:QUERY:MULTI?
    };
    const TrieNode _node_TEST_colonQUERY_colonMULT_children[] = {
        { 'I', 0, 1, _node_TEST_colonQUERY_colonMULTI_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonMUL_children[] = {
        { 'T', 0, 1, _node_TEST_colonQUERY_colonMULT_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonMU_children[] = {
        { 'L', 0, 1, _node_TEST_colonQUERY_colonMUL_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonM_children[] = {
        { 'U', 0, 1, _node_TEST_colonQUERY_colonMU_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonPARAM_children[] = {
        { '?', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 17 } // Terminal: TEST:QUERY:PARAM?
    };
    const TrieNode _node_TEST_colonQUERY_colonPARA_children[] = {
        { 'M', 0, 1, _node_TEST_colonQUERY_colonPARAM_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonPAR_children[] = {
        { 'A', 0, 1, _node_TEST_colonQUERY_colonPARA_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonPA_children[] = {
        { 'R', 0, 1, _node_TEST_colonQUERY_colonPAR_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colonP_children[] = {
        { 'A', 0, 1, _node_TEST_colonQUERY_colonPA_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_colon_children[] = {
        { 'M', 0, 1, _node_TEST_colonQUERY_colonM_children, 0 },
        { 'P', 0, 1, _node_TEST_colonQUERY_colonP_children, 0 }
    };
    const TrieNode _node_TEST_colonQUERY_children[] = {
        { ':', 0, 2, _node_TEST_colonQUERY_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonQUER_children[] = {
        { 'Y', 0, 1, _node_TEST_colonQUERY_children, 0 }
    };
    const TrieNode _node_TEST_colonQUE_children[] = {
        { 'R', 0, 1, _node_TEST_colonQUER_children, 0 }
    };
    const TrieNode _node_TEST_colonQU_children[] = {
        { 'E', 0, 1, _node_TEST_colonQUE_children, 0 }
    };
    const TrieNode _node_TEST_colonQ_children[] = {
        { 'U', 0, 1, _node_TEST_colonQU_children, 0 }
    };
    const TrieNode _node_TEST_colonSIMPLE_children[] = {
        { '?', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 1 } // Terminal: TEST:SIMPLE?
    };
    const TrieNode _node_TEST_colonSIMPL_children[] = {
        { 'E', uint8_t(TrieNodeFlags::Terminal), 1, _node_TEST_colonSIMPLE_children, 0 } // Terminal: TEST:SIMPLE
    };
    const TrieNode _node_TEST_colonSIMP_children[] = {
        { 'L', 0, 1, _node_TEST_colonSIMPL_children, 0 }
    };
    const TrieNode _node_TEST_colonSIM_children[] = {
        { 'P', 0, 1, _node_TEST_colonSIMP_children, 0 }
    };
    const TrieNode _node_TEST_colonSI_children[] = {
        { 'M', 0, 1, _node_TEST_colonSIM_children, 0 }
    };
    const TrieNode _node_TEST_colonSTRING_colonQUOTE_children[] = {
        { 'D', uint8_t(TrieNodeFlags::Terminal), 0, nullptr, 14 } // Terminal: TEST:STRING:QUOTED
    };
    const TrieNode _node_TEST_colonSTRING_colonQUOT_children[] = {
        { 'E', 0, 1, _node_TEST_colonSTRING_colonQUOTE_children, 0 }
    };
    const TrieNode _node_TEST_colonSTRING_colonQUO_children[] = {
        { 'T', 0, 1, _node_TEST_colonSTRING_colonQUOT_children, 0 }
    };
    const TrieNode _node_TEST_colonSTRING_colonQU_children[] = {
        { 'O', 0, 1, _node_TEST_colonSTRING_colonQUO_children, 0 }
    };
    const TrieNode _node_TEST_colonSTRING_colonQ_children[] = {
        { 'U', 0, 1, _node_TEST_colonSTRING_colonQU_children, 0 }
    };
    const TrieNode _node_TEST_colonSTRING_colon_children[] = {
        { 'Q', 0, 1, _node_TEST_colonSTRING_colonQ_children, 0 }
    };
    const TrieNode _node_TEST_colonSTRING_children[] = {
        { ':', 0, 1, _node_TEST_colonSTRING_colon_children, 0 }
    };
    const TrieNode _node_TEST_colonSTRIN_children[] = {
        { 'G', uint8_t(TrieNodeFlags::Terminal), 1, _node_TEST_colonSTRING_children, 5 } // Terminal: TEST:STRING
    };
    const TrieNode _node_TEST_colonSTRI_children[] = {
        { 'N', 0, 1, _node_TEST_colonSTRIN_children, 0 }
    };
    const TrieNode _node_TEST_colonSTR_children[] = {
        { 'I', 0, 1, _node_TEST_colonSTRI_children, 0 }
    };
    const TrieNode _node_TEST_colonST_children[] = {
        { 'R', 0, 1, _node_TEST_colonSTR_children, 0 }
    };
    const TrieNode _node_TEST_colonS_children[] = {
        { 'I', 0, 1, _node_TEST_colonSI_children, 0 },
        { 'T', 0, 1, _node_TEST_colonST_children, 0 }
    };
    const TrieNode _node_TEST_colon_children[] = {
        { 'A', 0, 1, _node_TEST_colonA_children, 0 },
        { 'B', 0, 1, _node_TEST_colonB_children, 0 },
        { 'C', 0, 1, _node_TEST_colonC_children, 0 },
        { 'E', 0, 2, _node_TEST_colonE_children, 0 },
        { 'M', 0, 1, _node_TEST_colonM_children, 0 },
        { 'N', 0, 1, _node_TEST_colonN_children, 0 },
        { 'O', 0, 1, _node_TEST_colonO_children, 0 },
        { 'Q', 0, 1, _node_TEST_colonQ_children, 0 },
        { 'S', 0, 2, _node_TEST_colonS_children, 0 }
    };
    const TrieNode _node_TEST_children[] = {
        { ':', 0, 9, _node_TEST_colon_children, 0 }
    };
    const TrieNode _node_TES_children[] = {
        { 'T', 0, 1, _node_TEST_children, 0 }
    };
    const TrieNode _node_TE_children[] = {
        { 'S', 0, 1, _node_TES_children, 0 }
    };
    const TrieNode _node_T_children[] = {
        { 'E', 0, 1, _node_TE_children, 0 }
    };
    const TrieNode _root_children[] = {
        { 'S', 0, 1, _node_S_children, 0 },
        { 'T', 0, 1, _node_T_children, 0 }
    };
    template<>
    const TrieNode T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter>::_trie = { '\0', 0, 2, _root_children, 0 };

    // Command handlers and parameters
    template<>
    const Command<T76::SCPI::ConcreteInterpreter> T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter>::_commands[] = {
        { &T76::SCPI::ConcreteInterpreter::_testSimple, 0, nullptr }, // TEST:SIMPLE
        { &T76::SCPI::ConcreteInterpreter::_queryTestSimple, 0, nullptr }, // TEST:SIMPLE?
        { &T76::SCPI::ConcreteInterpreter::_testMixedCase, 0, nullptr }, // TEST:COMmand:OPTional:SYNtax
        { &T76::SCPI::ConcreteInterpreter::_testABDSimple, 1, command_3_params }, // TEST:ABD:SIMPLE
        { &T76::SCPI::ConcreteInterpreter::_testNumber, 1, command_4_params }, // TEST:NUMBER
        { &T76::SCPI::ConcreteInterpreter::_testString, 1, command_5_params }, // TEST:STRING
        { &T76::SCPI::ConcreteInterpreter::_testBoolean, 1, command_6_params }, // TEST:BOOLEAN
        { &T76::SCPI::ConcreteInterpreter::_testEnum, 1, command_7_params }, // TEST:ENUM
        { &T76::SCPI::ConcreteInterpreter::_testMultiTwo, 2, command_8_params }, // TEST:MULTI:TWO
        { &T76::SCPI::ConcreteInterpreter::_testOptionalSingle, 2, command_9_params }, // TEST:OPTIONAL:SINGLE
        { &T76::SCPI::ConcreteInterpreter::_testOptionalMultiple, 3, command_10_params }, // TEST:OPTIONAL:MULTIPLE
        { &T76::SCPI::ConcreteInterpreter::_testInteger, 1, command_11_params }, // TEST:NUMERIC:INTEGER
        { &T76::SCPI::ConcreteInterpreter::_testFloat, 1, command_12_params }, // TEST:NUMERIC:FLOAT
        { &T76::SCPI::ConcreteInterpreter::_testRange, 2, command_13_params }, // TEST:NUMERIC:RANGE
        { &T76::SCPI::ConcreteInterpreter::_testQuotedString, 1, command_14_params }, // TEST:STRING:QUOTED
        { &T76::SCPI::ConcreteInterpreter::_testEnumMixed, 1, command_15_params }, // TEST:ENUM:MIXED
        { &T76::SCPI::ConcreteInterpreter::_testEnumNumeric, 1, command_16_params }, // TEST:ENUM:NUMERIC
        { &T76::SCPI::ConcreteInterpreter::_queryTestParam, 1, command_17_params }, // TEST:QUERY:PARAM?
        { &T76::SCPI::ConcreteInterpreter::_queryTestMulti, 2, command_18_params }, // TEST:QUERY:MULTI?
        { &T76::SCPI::ConcreteInterpreter::_testErrorSimulate, 1, command_19_params }, // TEST:ERROR:SIMULATE
        { &T76::SCPI::ConcreteInterpreter::_testErrorInvalid, 0, nullptr }, // TEST:ERROR:INVALID
        { &T76::SCPI::ConcreteInterpreter::_querySystemError, 0, nullptr }, // SYSTEM:ERROR?
    };

    template<>
    const size_t T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter>::_commandCount = 22;

    template<>
    const size_t T76::SCPI::Interpreter<T76::SCPI::ConcreteInterpreter>::_maxParameterCount = 3;

} // namespace
